<script setup lang="ts">
import { RouterLink } from 'vue-router'
</script>

<template>
  <div class="flex-grow max-w-3xl mx-auto w-full px-4 py-16">
    <div class="mb-12">
      <h1 class="text-4xl md:text-5xl font-extrabold text-white mb-6">About HeartSmart</h1>
      <p class="text-xl text-slate-400 leading-relaxed font-light">
        A portfolio piece built by <a href="#" class="text-rose-400 hover:text-rose-300 underline underline-offset-4 decoration-rose-500/30">John Whittenburg</a> to demonstrate practical, empathy-driven AI applications in frontend development.
      </p>
    </div>

    <div class="space-y-12 text-slate-300 leading-relaxed">
      
      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-white flex items-center gap-2">
          <span class="w-8 h-px bg-slate-700"></span> The Why
        </h2>
        <p>
          Following a cardiac event or the placement of a stent, patients are often handed a dense packet of dietary guidelines. The mandate is clear: lower sodium, reduce saturated fat, increase fiber. But the reality of implementing this at the dinner table is overwhelming.
        </p>
        <p>
          Favorite family recipes suddenly feel off-limits. Deciphering what to swap out—without making the meal taste like cardboard—becomes a source of deep anxiety. I built HeartSmart because I believe software should shoulder that cognitive load. 
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-white flex items-center gap-2">
          <span class="w-8 h-px bg-slate-700"></span> The How
        </h2>
        <p>
          This Minimum Viable Product uses a Vue 3 and Vite frontend paired with a Node.js/Fastify backend. It scrapes standard <code>schema.org</code> Recipe shapes from popular food blogs, and feeds the raw culinary data into Google's Gemini AI.
        </p>
        <p>
          Through careful prompting, the model acts as a culinary expert—identifying high-risk ingredients and offering realistic, flavorful substitutions that satisfy American Heart Association standards while keeping the soul of the dish intact. The results are then seamlessly bridged to Instacart to close the loop from intention to pantry.
        </p>
      </section>

      <section class="bg-slate-800/50 rounded-2xl p-6 md:p-8 border border-slate-700/50">
        <h3 class="text-xl font-bold text-white mb-4">Safety & Trust Disclaimer</h3>
        <p class="text-sm text-slate-400 space-y-2">
          <span class="block">&bull; This application provides general wellness-oriented recipe adaptations and is absolutely <strong class="text-slate-200">not medical advice.</strong></span>
          <span class="block">&bull; Nutrition details and optimizations are generated by a Large Language Model and may be approximate or occasionally hallucinated.</span>
          <span class="block">&bull; Users with medical conditions (like severe heart disease, diabetes, or hypertension) must verify all ingredients, portions, and substitutions with a registered dietitian or doctor.</span>
        </p>
      </section>

      <div class="pt-8 flex justify-center border-t border-slate-800">
        <RouterLink to="/" class="px-6 py-3 bg-slate-800 hover:bg-slate-700 rounded-xl text-white font-medium transition-colors">
          Try HeartSmart &rarr;
        </RouterLink>
      </div>

    </div>
  </div>
</template>
